library("tidyverse")
library("data.table")
library("ggplot2")
library("ggpubr")
library(ggbeeswarm)

# ------------------------------------------------------------------------------------------------------------
# analyze the known contamination levels from the experimentally mixed samples on the 10.3, v1 run
# ------------------------------------------------------------------------------------------------------------

# based on files generated by ./scripts/contamination/2022_01_19_merge_contamination_with_sample_sheet.ipynb

run_103 = fread("/analysis/2021_08_26_PlasmidSeq_paper/scripts/contamination/10_3_all.combined",fill=TRUE)
run_103 = run_103[run_103$assembly != "56_rotated.fasta",]
run_103 = run_103[order(run_103$plasmid),]

known_contamination_samples = run_103[run_103$plasmid >= 49 & run_103$plasmid <= 53,]
known_contamination_samples$rates = c(0,5,15,30,70) # ,85) # ,95) # leave out the two plasmids, 0.85 and 0.95%, we failed to assemble

cor(known_contamination_samples$contamination,known_contamination_samples$rates)
rmse(known_contamination_samples$contamination,known_contamination_samples$rates)

g = ggplot(known_contamination_samples,aes(rates,contamination)) + 
  geom_point(size=2) + 
  theme_classic() + 
  xlab("Known contamination rate") + 
  ylab("Predicted contamination rate") +
  geom_smooth(method = "lm", se=TRUE, color="black", formula = y ~ x)

ggsave(g,file="/analysis/2021_08_26_PlasmidSeq_paper/figures/figure_4/known_contamination_experimental_2022_01_19.pdf",width=2,height=3)
ggsave(g,file="/analysis/2021_08_26_PlasmidSeq_paper/figures/figure_4/known_contamination_experimental_2022_01_19.png",width=2,height=3)


# ------------------------------------------------------------------------------------------------------------
# analyze both the 10.3 and 9.4 runs together
# ------------------------------------------------------------------------------------------------------------

# based on files generated by ./scripts/contamination/2022_01_19_merge_contamination_with_sample_sheet.ipynb

contam = fread("/analysis/2021_08_26_PlasmidSeq_paper/scripts/contamination/9_4_v2_all.combinedd")
contam$complete = (1.0 - abs(1.0 - contam$contiguity)) * (1.0 - abs(1.0 - contam$identity))
contam$run = "9.4"
contam$barcodes = "v2"


run_103 = fread("/analysis/2021_08_26_PlasmidSeq_paper/scripts/contamination/10_3_all.combined",fill=TRUE)
run_103 = run_103[run_103$plasmid < 49 | run_103$plasmid > 55,]

run_103$complete = (1.0 - abs(1.0 - run_103$contiguity)) * (1.0 - abs(1.0 - run_103$identity))
run_103$run = "10.3"
run_103$barcodes = "v1"

full_94_103_run = rbind(contam,run_103)

g = ggplot(full_94_103_run,aes(complete,contamination,fill=run)) + geom_point(color="black",size=3,shape=21,stroke =1) + 
  theme_classic() + 
  ylab("Contamination rate") + 
  xlab("Completeness") + 
  xlim(c(0.5,1)) + 
  ylim(c(0,50))  

ggsave(g,file="/analysis/2021_08_26_PlasmidSeq_paper/figures/figure_4/real_94_103_contamination_assembly_2022_01_19.pdf",width=3,height=3)
ggsave(g,file="/analysis/2021_08_26_PlasmidSeq_paper/figures/figure_4/real_94_103_contamination_assembly_2022_01_19.png",width=3,height=3)


g = ggplot(full_94_103_run,aes(x=barcodes,y=contamination,fill=barcodes)) + geom_quasirandom(size=1,shape=21,stroke =0.3) +
  theme_classic() + 
  xlab("Value") + 
  scale_fill_manual(values = c("#0066ff","#ff5050"))

ggsave(g,file="/analysis/2021_08_26_PlasmidSeq_paper/figures/figure_4/aggregate_contamination_2022_01_20.pdf",width=3,height=3)
ggsave(g,file="/analysis/2021_08_26_PlasmidSeq_paper/figures/figure_4/aggregate_contamination_2022_01_20.png",width=3,height=3)

# ------------------------------------------------------------------------------------------------------------
# significance of our barcode improvement on contamination levels
# ------------------------------------------------------------------------------------------------------------
summary(aov(contamination ~ run, data = full_94_103_run))
summary(aov(contamination ~ run, data = full_94_103_run[full_94_103_run$contamination < 30,]))


# ------------------------------------------------------------------------------------------------------------
# correlations between the contamination level and combined assembly issues
# ------------------------------------------------------------------------------------------------------------
cor(full_94_103_run$contamination, full_94_103_run$complete)
cor(full_94_103_run[full_94_103_run$run == "10.3",]$contamination, full_94_103_run[full_94_103_run$run == "10.3",]$complete)
cor(full_94_103_run[full_94_103_run$run == "9.4",]$contamination, full_94_103_run[full_94_103_run$run == "9.4",]$complete)