[loading_options]
barcodes_filename = "barcodes_masked.fasta"
lamp_targets_filename = "ncov_targets.fasta"
double_variants_frontrear = true

# ############### LAMP barcodes ###############

[arrangement]
name = "barcode_arrs_ncov96"
id_pattern = "LAMP%02i"
compatible_kits = ["OND-SQK-LP9216","OND-SQK-LP1152S"]
first_index = 1
last_index = 8
kit = "LAMP"
normalised_id_pattern = "FIP%02i"
barcode1_pattern = "LM%02i"
lamp_masks = ["human_ACTB","nCoV2019_E1","nCoV2019_N2","nCoV2019_AS1"]
