####################
#
# Barcode Design 2
#
####################
#
#  2-Barcode Arrangement Variant 1:
#  
#         BCXX_1st                           BCXX_2nd
#  FWD  >-=====------------------------------=====-\
#                                                   |
#  REV  <-=====------------------------------=====-/
#         BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_1st_FWD----------BCXX_2nd_REV
#
###
#
#  2-Barcode Arrangement Variant 2:
#
#     BCXX_1st                           BCXX_2nd
#   /-=====------------------------------=====->  REV
#  |
#   \-=====------------------------------=====-<  FWD
#     BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_2nd_FWD----------BCXX_1st_REV
#
#  the sequences BCXX_1st and BCXX_2nd will be equal
#  for most of their parts, especially for the main barcode.
#  They will usually only differ in the rear spacer between
#  barcode and (actual) strand.
#
####################

[loading_options]
barcodes_filename = "barcodes_masked.fasta"
double_variants_frontrear = true

# ############### Native barcoding kit ###############

[arrangement]
name = "barcode_arrs_nb24"
id_pattern = "NB%02i"
compatible_kits = ["SQK-NBD110-24","SQK-NBD111-24","SQK-NBD112-24"]
first_index = 1
last_index = 24
kit = "NB"
normalised_id_pattern = "barcode%02i"
scoring_function = "MAX"
mask1 = "NB_1st"
mask2 = "NB_2nd"
barcode1_pattern = "NB%02i"
barcode2_pattern = "NB%02i"
