####################
#
# Barcode Design 2
#
####################
#
#  This is distinct from barcode_arrs_vmk because it uses barcode kit RBK4, barcodes 1-10.
#
#  2-Barcode Arrangement Variant 1:
#  
#         RBKXX_1st                           RBKXX_2nd
#  FWD  >-=====------------------------------=====-\
#                                                   |
#  REV  <-=====------------------------------=====-/
#         RBKXX_1st                           RBKXX_2nd
#
#  leads to basecall RBKXX_1st_FWD----------RBKXX_2nd_REV
#
###
#
#  2-Barcode Arrangement Variant 2:
#
#     RBKXX_1st                           RBKXX_2nd
#   /-=====------------------------------=====->  REV
#  |
#   \-=====------------------------------=====-<  FWD
#     RBKXX_1st                           RBKXX_2nd
#
#  leads to basecall RBKXX_2nd_FWD----------RBKXX_1st_REV
#
#  the sequences RBKXX_1st and RBKXX_2nd will be equal
#  for most of their parts, especially for the main barcode.
#  They will usually only differ in the rear spacer between
#  barcode and (actual) strand.
#
####################

[loading_options]
barcodes_filename = "barcodes_masked.fasta"
double_variants_frontrear = false

# ############### Rapid barcoding RBK004 kit ###############

[arrangement]
name = "barcode_arrs_vmk2"
id_pattern = "RBK4%02i"
compatible_kits = ["VSK-VMK002","VSK-VMK003"]
first_index = 1
last_index = 10
kit = "RBK4"
normalised_id_pattern = "barcode%02i"
mask1 = "RBK4"
barcode1_pattern = "BC%02i"

