####################
#
# Barcode Design 2
#
####################
#
#  This is distinct from barcode_arrs_rbk because the downstream context has changed.
#
#  2-Barcode Arrangement Variant 1:
#
#         BCXX_1st                           BCXX_2nd
#  FWD  >-=====------------------------------=====-\
#                                                   |
#  REV  <-=====------------------------------=====-/
#         BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_1st_FWD----------BCXX_2nd_REV
#
###
#
#  2-Barcode Arrangement Variant 2:
#
#     BCXX_1st                           BCXX_2nd
#   /-=====------------------------------=====->  REV
#  |
#   \-=====------------------------------=====-<  FWD
#     BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_2nd_FWD----------BCXX_1st_REV
#
#  the sequences BCXX_1st and BCXX_2nd will be equal
#  for most of their parts, especially for the main barcode.
#  They will usually only differ in the rear spacer between
#  barcode and (actual) strand.
#
####################

[loading_options]
barcodes_filename = "barcodes_masked.fasta"
double_variants_frontrear = false

# ############### Rapid barcoding RBK004 kit ###############

[arrangement]
name = "barcode_arrs_rbk4"
id_pattern = "RBK4%02i"
compatible_kits = ["SQK-RBK004","OND-SQK-LP0096S","OND-SQK-LP0096M","OND-SQK-LP0096MA","VSK-PTC001"]
first_index = 1
last_index = 12
kit = "RBK4"
normalised_id_pattern = "barcode%02i"
mask1 = "RBK4"
barcode1_pattern = "RBK%02i"
